- ## installation
	- `sudo apt-get update && sudo apt-get install apt-transport-https ca-certificates curl gnupg2 software-properties-common`
	- `curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -`
	- `sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"`
	- `sudo apt update && sudo apt-get install docker-ce docker-ce-cli containerd.io`
	- Ajouter l'utilisateur au groupe docker :
		- `sudo usermod -aG docker <user>`
-
- ## Sources
	- https://openclassrooms.com/fr/courses/2035766-optimisez-votre-deploiement-en-creant-des-conteneurs-avec-docker/6211390-installez-docker-sur-votre-poste